version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "s3://laasbucket"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 16
    commands:
        - echo Installing source NPM dependencies ....
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started
        - npm run build
  post_build:      
    commands:
        - echo build process finished, we should uplload to S3 now
        - cd dist/$APP_NAME
        - ls -la
        - aws s3 sync . s3://laasbucket      
